source "https://rubygems.org"
# copied from sinatra app

# day 1
gem 'sinatra'

# page 3
gem 'rspec'
gem 'rack-test'

# page 6
gem 'sqlite3'
gem 'data_mapper'
gem 'dm-sqlite-adapter'

# day 2 - views
# page 13 - handling json and html requests
gem 'sinatra-contrib'

# page 18
gem 'slim'

gem 'mustache'
gem 'sinatra-mustache'



# for complete -
gem 'capybara'
gem 'launchy'
